// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package com.thanos.api.proto.sync;

public final class SyncGrpcTransport {
  private SyncGrpcTransport() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_thanos_api_proto_sync_DefaultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_thanos_api_proto_sync_DefaultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_thanos_api_proto_sync_DefaultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_thanos_api_proto_sync_DefaultResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_thanos_api_proto_sync_BlockBytesObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_thanos_api_proto_sync_BlockBytesObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nsync.proto\022\031com.thanos.api.proto.sync\"" +
      "\035\n\016DefaultRequest\022\013\n\003req\030\001 \001(\t\"!\n\017Defaul" +
      "tResponse\022\016\n\006result\030\001 \001(\010\")\n\020BlockBytesO" +
      "bject\022\025\n\rblockBaseInfo\030\001 \001(\0142u\n\013SyncServ" +
      "ice\022f\n\tsyncBlock\022+.com.thanos.api.proto." +
      "sync.BlockBytesObject\032*.com.thanos.api.p" +
      "roto.sync.DefaultResponse\"\000B0\n\031com.thano" +
      "s.api.proto.syncB\021SyncGrpcTransportP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_thanos_api_proto_sync_DefaultRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_thanos_api_proto_sync_DefaultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_thanos_api_proto_sync_DefaultRequest_descriptor,
        new java.lang.String[] { "Req", });
    internal_static_com_thanos_api_proto_sync_DefaultResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_thanos_api_proto_sync_DefaultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_thanos_api_proto_sync_DefaultResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_thanos_api_proto_sync_BlockBytesObject_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_thanos_api_proto_sync_BlockBytesObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_thanos_api_proto_sync_BlockBytesObject_descriptor,
        new java.lang.String[] { "BlockBaseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
