// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.thanos.api.proto.push;

public interface BlockBytesObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.push.BlockBytesObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes blockBaseInfo = 1;</code>
   * @return The blockBaseInfo.
   */
  com.google.protobuf.ByteString getBlockBaseInfo();
}
