// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.thanos.api.proto.push;

public interface DefaultRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.push.DefaultRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string req = 1;</code>
   * @return The req.
   */
  java.lang.String getReq();
  /**
   * <code>string req = 1;</code>
   * @return The bytes for req.
   */
  com.google.protobuf.ByteString
      getReqBytes();
}
