// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.thanos.api.proto.push;

/**
 * Protobuf type {@code com.thanos.api.proto.push.EthTransactionsPushDTO}
 */
public final class EthTransactionsPushDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.thanos.api.proto.push.EthTransactionsPushDTO)
    EthTransactionsPushDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EthTransactionsPushDTO.newBuilder() to construct.
  private EthTransactionsPushDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EthTransactionsPushDTO() {
    txs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EthTransactionsPushDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EthTransactionsPushDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              txs_ = new java.util.ArrayList<com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO>();
              mutable_bitField0_ |= 0x00000001;
            }
            txs_.add(
                input.readMessage(com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        txs_ = java.util.Collections.unmodifiableList(txs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_EthTransactionsPushDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_EthTransactionsPushDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.thanos.api.proto.push.EthTransactionsPushDTO.class, com.thanos.api.proto.push.EthTransactionsPushDTO.Builder.class);
  }

  public interface EthTransactionPushDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes publicKey = 1;</code>
     * @return The publicKey.
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <code>bytes nonce = 2;</code>
     * @return The nonce.
     */
    com.google.protobuf.ByteString getNonce();

    /**
     * <code>int64 futureEventNumber = 3;</code>
     * @return The futureEventNumber.
     */
    long getFutureEventNumber();

    /**
     * <code>bytes gasPrice = 4;</code>
     * @return The gasPrice.
     */
    com.google.protobuf.ByteString getGasPrice();

    /**
     * <code>bytes gasLimit = 5;</code>
     * @return The gasLimit.
     */
    com.google.protobuf.ByteString getGasLimit();

    /**
     * <code>bytes receiveAddress = 6;</code>
     * @return The receiveAddress.
     */
    com.google.protobuf.ByteString getReceiveAddress();

    /**
     * <code>bytes value = 7;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>bytes data = 8;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>repeated bytes executeStates = 9;</code>
     * @return A list containing the executeStates.
     */
    java.util.List<com.google.protobuf.ByteString> getExecuteStatesList();
    /**
     * <code>repeated bytes executeStates = 9;</code>
     * @return The count of executeStates.
     */
    int getExecuteStatesCount();
    /**
     * <code>repeated bytes executeStates = 9;</code>
     * @param index The index of the element to return.
     * @return The executeStates at the given index.
     */
    com.google.protobuf.ByteString getExecuteStates(int index);

    /**
     * <code>bytes signature = 10;</code>
     * @return The signature.
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>bytes hash = 11;</code>
     * @return The hash.
     */
    com.google.protobuf.ByteString getHash();

    /**
     * <code>bytes rlpEncoded = 12;</code>
     * @return The rlpEncoded.
     */
    com.google.protobuf.ByteString getRlpEncoded();
  }
  /**
   * Protobuf type {@code com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO}
   */
  public static final class EthTransactionPushDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO)
      EthTransactionPushDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EthTransactionPushDTO.newBuilder() to construct.
    private EthTransactionPushDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EthTransactionPushDTO() {
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      nonce_ = com.google.protobuf.ByteString.EMPTY;
      gasPrice_ = com.google.protobuf.ByteString.EMPTY;
      gasLimit_ = com.google.protobuf.ByteString.EMPTY;
      receiveAddress_ = com.google.protobuf.ByteString.EMPTY;
      value_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
      executeStates_ = java.util.Collections.emptyList();
      signature_ = com.google.protobuf.ByteString.EMPTY;
      hash_ = com.google.protobuf.ByteString.EMPTY;
      rlpEncoded_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EthTransactionPushDTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EthTransactionPushDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              publicKey_ = input.readBytes();
              break;
            }
            case 18: {

              nonce_ = input.readBytes();
              break;
            }
            case 24: {

              futureEventNumber_ = input.readInt64();
              break;
            }
            case 34: {

              gasPrice_ = input.readBytes();
              break;
            }
            case 42: {

              gasLimit_ = input.readBytes();
              break;
            }
            case 50: {

              receiveAddress_ = input.readBytes();
              break;
            }
            case 58: {

              value_ = input.readBytes();
              break;
            }
            case 66: {

              data_ = input.readBytes();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                executeStates_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              executeStates_.add(input.readBytes());
              break;
            }
            case 82: {

              signature_ = input.readBytes();
              break;
            }
            case 90: {

              hash_ = input.readBytes();
              break;
            }
            case 98: {

              rlpEncoded_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          executeStates_ = java.util.Collections.unmodifiableList(executeStates_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_EthTransactionsPushDTO_EthTransactionPushDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_EthTransactionsPushDTO_EthTransactionPushDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.class, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder.class);
    }

    public static final int PUBLICKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>bytes publicKey = 1;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int NONCE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString nonce_;
    /**
     * <code>bytes nonce = 2;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }

    public static final int FUTUREEVENTNUMBER_FIELD_NUMBER = 3;
    private long futureEventNumber_;
    /**
     * <code>int64 futureEventNumber = 3;</code>
     * @return The futureEventNumber.
     */
    @java.lang.Override
    public long getFutureEventNumber() {
      return futureEventNumber_;
    }

    public static final int GASPRICE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString gasPrice_;
    /**
     * <code>bytes gasPrice = 4;</code>
     * @return The gasPrice.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGasPrice() {
      return gasPrice_;
    }

    public static final int GASLIMIT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString gasLimit_;
    /**
     * <code>bytes gasLimit = 5;</code>
     * @return The gasLimit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGasLimit() {
      return gasLimit_;
    }

    public static final int RECEIVEADDRESS_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString receiveAddress_;
    /**
     * <code>bytes receiveAddress = 6;</code>
     * @return The receiveAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getReceiveAddress() {
      return receiveAddress_;
    }

    public static final int VALUE_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>bytes value = 7;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int DATA_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 8;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int EXECUTESTATES_FIELD_NUMBER = 9;
    private java.util.List<com.google.protobuf.ByteString> executeStates_;
    /**
     * <code>repeated bytes executeStates = 9;</code>
     * @return A list containing the executeStates.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getExecuteStatesList() {
      return executeStates_;
    }
    /**
     * <code>repeated bytes executeStates = 9;</code>
     * @return The count of executeStates.
     */
    public int getExecuteStatesCount() {
      return executeStates_.size();
    }
    /**
     * <code>repeated bytes executeStates = 9;</code>
     * @param index The index of the element to return.
     * @return The executeStates at the given index.
     */
    public com.google.protobuf.ByteString getExecuteStates(int index) {
      return executeStates_.get(index);
    }

    public static final int SIGNATURE_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 10;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int HASH_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString hash_;
    /**
     * <code>bytes hash = 11;</code>
     * @return The hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    public static final int RLPENCODED_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString rlpEncoded_;
    /**
     * <code>bytes rlpEncoded = 12;</code>
     * @return The rlpEncoded.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRlpEncoded() {
      return rlpEncoded_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!publicKey_.isEmpty()) {
        output.writeBytes(1, publicKey_);
      }
      if (!nonce_.isEmpty()) {
        output.writeBytes(2, nonce_);
      }
      if (futureEventNumber_ != 0L) {
        output.writeInt64(3, futureEventNumber_);
      }
      if (!gasPrice_.isEmpty()) {
        output.writeBytes(4, gasPrice_);
      }
      if (!gasLimit_.isEmpty()) {
        output.writeBytes(5, gasLimit_);
      }
      if (!receiveAddress_.isEmpty()) {
        output.writeBytes(6, receiveAddress_);
      }
      if (!value_.isEmpty()) {
        output.writeBytes(7, value_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(8, data_);
      }
      for (int i = 0; i < executeStates_.size(); i++) {
        output.writeBytes(9, executeStates_.get(i));
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(10, signature_);
      }
      if (!hash_.isEmpty()) {
        output.writeBytes(11, hash_);
      }
      if (!rlpEncoded_.isEmpty()) {
        output.writeBytes(12, rlpEncoded_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!publicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, publicKey_);
      }
      if (!nonce_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, nonce_);
      }
      if (futureEventNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, futureEventNumber_);
      }
      if (!gasPrice_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, gasPrice_);
      }
      if (!gasLimit_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, gasLimit_);
      }
      if (!receiveAddress_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, receiveAddress_);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, value_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, data_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < executeStates_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(executeStates_.get(i));
        }
        size += dataSize;
        size += 1 * getExecuteStatesList().size();
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, signature_);
      }
      if (!hash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, hash_);
      }
      if (!rlpEncoded_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, rlpEncoded_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO)) {
        return super.equals(obj);
      }
      com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO other = (com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO) obj;

      if (!getPublicKey()
          .equals(other.getPublicKey())) return false;
      if (!getNonce()
          .equals(other.getNonce())) return false;
      if (getFutureEventNumber()
          != other.getFutureEventNumber()) return false;
      if (!getGasPrice()
          .equals(other.getGasPrice())) return false;
      if (!getGasLimit()
          .equals(other.getGasLimit())) return false;
      if (!getReceiveAddress()
          .equals(other.getReceiveAddress())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getExecuteStatesList()
          .equals(other.getExecuteStatesList())) return false;
      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (!getHash()
          .equals(other.getHash())) return false;
      if (!getRlpEncoded()
          .equals(other.getRlpEncoded())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + getNonce().hashCode();
      hash = (37 * hash) + FUTUREEVENTNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFutureEventNumber());
      hash = (37 * hash) + GASPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getGasPrice().hashCode();
      hash = (37 * hash) + GASLIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getGasLimit().hashCode();
      hash = (37 * hash) + RECEIVEADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getReceiveAddress().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      if (getExecuteStatesCount() > 0) {
        hash = (37 * hash) + EXECUTESTATES_FIELD_NUMBER;
        hash = (53 * hash) + getExecuteStatesList().hashCode();
      }
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (37 * hash) + RLPENCODED_FIELD_NUMBER;
      hash = (53 * hash) + getRlpEncoded().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO)
        com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_EthTransactionsPushDTO_EthTransactionPushDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_EthTransactionsPushDTO_EthTransactionPushDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.class, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder.class);
      }

      // Construct using com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        publicKey_ = com.google.protobuf.ByteString.EMPTY;

        nonce_ = com.google.protobuf.ByteString.EMPTY;

        futureEventNumber_ = 0L;

        gasPrice_ = com.google.protobuf.ByteString.EMPTY;

        gasLimit_ = com.google.protobuf.ByteString.EMPTY;

        receiveAddress_ = com.google.protobuf.ByteString.EMPTY;

        value_ = com.google.protobuf.ByteString.EMPTY;

        data_ = com.google.protobuf.ByteString.EMPTY;

        executeStates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        signature_ = com.google.protobuf.ByteString.EMPTY;

        hash_ = com.google.protobuf.ByteString.EMPTY;

        rlpEncoded_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_EthTransactionsPushDTO_EthTransactionPushDTO_descriptor;
      }

      @java.lang.Override
      public com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO getDefaultInstanceForType() {
        return com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.getDefaultInstance();
      }

      @java.lang.Override
      public com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO build() {
        com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO buildPartial() {
        com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO result = new com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO(this);
        int from_bitField0_ = bitField0_;
        result.publicKey_ = publicKey_;
        result.nonce_ = nonce_;
        result.futureEventNumber_ = futureEventNumber_;
        result.gasPrice_ = gasPrice_;
        result.gasLimit_ = gasLimit_;
        result.receiveAddress_ = receiveAddress_;
        result.value_ = value_;
        result.data_ = data_;
        if (((bitField0_ & 0x00000001) != 0)) {
          executeStates_ = java.util.Collections.unmodifiableList(executeStates_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.executeStates_ = executeStates_;
        result.signature_ = signature_;
        result.hash_ = hash_;
        result.rlpEncoded_ = rlpEncoded_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO) {
          return mergeFrom((com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO other) {
        if (other == com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.getDefaultInstance()) return this;
        if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setPublicKey(other.getPublicKey());
        }
        if (other.getNonce() != com.google.protobuf.ByteString.EMPTY) {
          setNonce(other.getNonce());
        }
        if (other.getFutureEventNumber() != 0L) {
          setFutureEventNumber(other.getFutureEventNumber());
        }
        if (other.getGasPrice() != com.google.protobuf.ByteString.EMPTY) {
          setGasPrice(other.getGasPrice());
        }
        if (other.getGasLimit() != com.google.protobuf.ByteString.EMPTY) {
          setGasLimit(other.getGasLimit());
        }
        if (other.getReceiveAddress() != com.google.protobuf.ByteString.EMPTY) {
          setReceiveAddress(other.getReceiveAddress());
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.executeStates_.isEmpty()) {
          if (executeStates_.isEmpty()) {
            executeStates_ = other.executeStates_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureExecuteStatesIsMutable();
            executeStates_.addAll(other.executeStates_);
          }
          onChanged();
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        if (other.getHash() != com.google.protobuf.ByteString.EMPTY) {
          setHash(other.getHash());
        }
        if (other.getRlpEncoded() != com.google.protobuf.ByteString.EMPTY) {
          setRlpEncoded(other.getRlpEncoded());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes publicKey = 1;</code>
       * @return The publicKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>bytes publicKey = 1;</code>
       * @param value The publicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes publicKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKey() {
        
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString nonce_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes nonce = 2;</code>
       * @return The nonce.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getNonce() {
        return nonce_;
      }
      /**
       * <code>bytes nonce = 2;</code>
       * @param value The nonce to set.
       * @return This builder for chaining.
       */
      public Builder setNonce(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes nonce = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNonce() {
        
        nonce_ = getDefaultInstance().getNonce();
        onChanged();
        return this;
      }

      private long futureEventNumber_ ;
      /**
       * <code>int64 futureEventNumber = 3;</code>
       * @return The futureEventNumber.
       */
      @java.lang.Override
      public long getFutureEventNumber() {
        return futureEventNumber_;
      }
      /**
       * <code>int64 futureEventNumber = 3;</code>
       * @param value The futureEventNumber to set.
       * @return This builder for chaining.
       */
      public Builder setFutureEventNumber(long value) {
        
        futureEventNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 futureEventNumber = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFutureEventNumber() {
        
        futureEventNumber_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString gasPrice_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes gasPrice = 4;</code>
       * @return The gasPrice.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGasPrice() {
        return gasPrice_;
      }
      /**
       * <code>bytes gasPrice = 4;</code>
       * @param value The gasPrice to set.
       * @return This builder for chaining.
       */
      public Builder setGasPrice(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gasPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes gasPrice = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasPrice() {
        
        gasPrice_ = getDefaultInstance().getGasPrice();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString gasLimit_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes gasLimit = 5;</code>
       * @return The gasLimit.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGasLimit() {
        return gasLimit_;
      }
      /**
       * <code>bytes gasLimit = 5;</code>
       * @param value The gasLimit to set.
       * @return This builder for chaining.
       */
      public Builder setGasLimit(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gasLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes gasLimit = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasLimit() {
        
        gasLimit_ = getDefaultInstance().getGasLimit();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString receiveAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes receiveAddress = 6;</code>
       * @return The receiveAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getReceiveAddress() {
        return receiveAddress_;
      }
      /**
       * <code>bytes receiveAddress = 6;</code>
       * @param value The receiveAddress to set.
       * @return This builder for chaining.
       */
      public Builder setReceiveAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiveAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes receiveAddress = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiveAddress() {
        
        receiveAddress_ = getDefaultInstance().getReceiveAddress();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 7;</code>
       * @return The value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 7;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 8;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 8;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> executeStates_ = java.util.Collections.emptyList();
      private void ensureExecuteStatesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          executeStates_ = new java.util.ArrayList<com.google.protobuf.ByteString>(executeStates_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes executeStates = 9;</code>
       * @return A list containing the executeStates.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getExecuteStatesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(executeStates_) : executeStates_;
      }
      /**
       * <code>repeated bytes executeStates = 9;</code>
       * @return The count of executeStates.
       */
      public int getExecuteStatesCount() {
        return executeStates_.size();
      }
      /**
       * <code>repeated bytes executeStates = 9;</code>
       * @param index The index of the element to return.
       * @return The executeStates at the given index.
       */
      public com.google.protobuf.ByteString getExecuteStates(int index) {
        return executeStates_.get(index);
      }
      /**
       * <code>repeated bytes executeStates = 9;</code>
       * @param index The index to set the value at.
       * @param value The executeStates to set.
       * @return This builder for chaining.
       */
      public Builder setExecuteStates(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureExecuteStatesIsMutable();
        executeStates_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes executeStates = 9;</code>
       * @param value The executeStates to add.
       * @return This builder for chaining.
       */
      public Builder addExecuteStates(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureExecuteStatesIsMutable();
        executeStates_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes executeStates = 9;</code>
       * @param values The executeStates to add.
       * @return This builder for chaining.
       */
      public Builder addAllExecuteStates(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureExecuteStatesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, executeStates_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes executeStates = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecuteStates() {
        executeStates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 10;</code>
       * @return The signature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 10;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes hash = 11;</code>
       * @return The hash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <code>bytes hash = 11;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes hash = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rlpEncoded_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes rlpEncoded = 12;</code>
       * @return The rlpEncoded.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRlpEncoded() {
        return rlpEncoded_;
      }
      /**
       * <code>bytes rlpEncoded = 12;</code>
       * @param value The rlpEncoded to set.
       * @return This builder for chaining.
       */
      public Builder setRlpEncoded(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rlpEncoded_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes rlpEncoded = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearRlpEncoded() {
        
        rlpEncoded_ = getDefaultInstance().getRlpEncoded();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO)
    }

    // @@protoc_insertion_point(class_scope:com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO)
    private static final com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO();
    }

    public static com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EthTransactionPushDTO>
        PARSER = new com.google.protobuf.AbstractParser<EthTransactionPushDTO>() {
      @java.lang.Override
      public EthTransactionPushDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EthTransactionPushDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EthTransactionPushDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EthTransactionPushDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int TXS_FIELD_NUMBER = 1;
  private java.util.List<com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO> txs_;
  /**
   * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO> getTxsList() {
    return txs_;
  }
  /**
   * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTOOrBuilder> 
      getTxsOrBuilderList() {
    return txs_;
  }
  /**
   * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
   */
  @java.lang.Override
  public int getTxsCount() {
    return txs_.size();
  }
  /**
   * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
   */
  @java.lang.Override
  public com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO getTxs(int index) {
    return txs_.get(index);
  }
  /**
   * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
   */
  @java.lang.Override
  public com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTOOrBuilder getTxsOrBuilder(
      int index) {
    return txs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < txs_.size(); i++) {
      output.writeMessage(1, txs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < txs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, txs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.thanos.api.proto.push.EthTransactionsPushDTO)) {
      return super.equals(obj);
    }
    com.thanos.api.proto.push.EthTransactionsPushDTO other = (com.thanos.api.proto.push.EthTransactionsPushDTO) obj;

    if (!getTxsList()
        .equals(other.getTxsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTxsCount() > 0) {
      hash = (37 * hash) + TXS_FIELD_NUMBER;
      hash = (53 * hash) + getTxsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.push.EthTransactionsPushDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.thanos.api.proto.push.EthTransactionsPushDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.thanos.api.proto.push.EthTransactionsPushDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.thanos.api.proto.push.EthTransactionsPushDTO)
      com.thanos.api.proto.push.EthTransactionsPushDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_EthTransactionsPushDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_EthTransactionsPushDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thanos.api.proto.push.EthTransactionsPushDTO.class, com.thanos.api.proto.push.EthTransactionsPushDTO.Builder.class);
    }

    // Construct using com.thanos.api.proto.push.EthTransactionsPushDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTxsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (txsBuilder_ == null) {
        txs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        txsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_EthTransactionsPushDTO_descriptor;
    }

    @java.lang.Override
    public com.thanos.api.proto.push.EthTransactionsPushDTO getDefaultInstanceForType() {
      return com.thanos.api.proto.push.EthTransactionsPushDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.thanos.api.proto.push.EthTransactionsPushDTO build() {
      com.thanos.api.proto.push.EthTransactionsPushDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.thanos.api.proto.push.EthTransactionsPushDTO buildPartial() {
      com.thanos.api.proto.push.EthTransactionsPushDTO result = new com.thanos.api.proto.push.EthTransactionsPushDTO(this);
      int from_bitField0_ = bitField0_;
      if (txsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          txs_ = java.util.Collections.unmodifiableList(txs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.txs_ = txs_;
      } else {
        result.txs_ = txsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.thanos.api.proto.push.EthTransactionsPushDTO) {
        return mergeFrom((com.thanos.api.proto.push.EthTransactionsPushDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.thanos.api.proto.push.EthTransactionsPushDTO other) {
      if (other == com.thanos.api.proto.push.EthTransactionsPushDTO.getDefaultInstance()) return this;
      if (txsBuilder_ == null) {
        if (!other.txs_.isEmpty()) {
          if (txs_.isEmpty()) {
            txs_ = other.txs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTxsIsMutable();
            txs_.addAll(other.txs_);
          }
          onChanged();
        }
      } else {
        if (!other.txs_.isEmpty()) {
          if (txsBuilder_.isEmpty()) {
            txsBuilder_.dispose();
            txsBuilder_ = null;
            txs_ = other.txs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            txsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTxsFieldBuilder() : null;
          } else {
            txsBuilder_.addAllMessages(other.txs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.thanos.api.proto.push.EthTransactionsPushDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.thanos.api.proto.push.EthTransactionsPushDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO> txs_ =
      java.util.Collections.emptyList();
    private void ensureTxsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        txs_ = new java.util.ArrayList<com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO>(txs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTOOrBuilder> txsBuilder_;

    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public java.util.List<com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO> getTxsList() {
      if (txsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(txs_);
      } else {
        return txsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public int getTxsCount() {
      if (txsBuilder_ == null) {
        return txs_.size();
      } else {
        return txsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO getTxs(int index) {
      if (txsBuilder_ == null) {
        return txs_.get(index);
      } else {
        return txsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public Builder setTxs(
        int index, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO value) {
      if (txsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTxsIsMutable();
        txs_.set(index, value);
        onChanged();
      } else {
        txsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public Builder setTxs(
        int index, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder builderForValue) {
      if (txsBuilder_ == null) {
        ensureTxsIsMutable();
        txs_.set(index, builderForValue.build());
        onChanged();
      } else {
        txsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public Builder addTxs(com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO value) {
      if (txsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTxsIsMutable();
        txs_.add(value);
        onChanged();
      } else {
        txsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public Builder addTxs(
        int index, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO value) {
      if (txsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTxsIsMutable();
        txs_.add(index, value);
        onChanged();
      } else {
        txsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public Builder addTxs(
        com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder builderForValue) {
      if (txsBuilder_ == null) {
        ensureTxsIsMutable();
        txs_.add(builderForValue.build());
        onChanged();
      } else {
        txsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public Builder addTxs(
        int index, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder builderForValue) {
      if (txsBuilder_ == null) {
        ensureTxsIsMutable();
        txs_.add(index, builderForValue.build());
        onChanged();
      } else {
        txsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public Builder addAllTxs(
        java.lang.Iterable<? extends com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO> values) {
      if (txsBuilder_ == null) {
        ensureTxsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, txs_);
        onChanged();
      } else {
        txsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public Builder clearTxs() {
      if (txsBuilder_ == null) {
        txs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        txsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public Builder removeTxs(int index) {
      if (txsBuilder_ == null) {
        ensureTxsIsMutable();
        txs_.remove(index);
        onChanged();
      } else {
        txsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder getTxsBuilder(
        int index) {
      return getTxsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTOOrBuilder getTxsOrBuilder(
        int index) {
      if (txsBuilder_ == null) {
        return txs_.get(index);  } else {
        return txsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public java.util.List<? extends com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTOOrBuilder> 
         getTxsOrBuilderList() {
      if (txsBuilder_ != null) {
        return txsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(txs_);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder addTxsBuilder() {
      return getTxsFieldBuilder().addBuilder(
          com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder addTxsBuilder(
        int index) {
      return getTxsFieldBuilder().addBuilder(
          index, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
     */
    public java.util.List<com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder> 
         getTxsBuilderList() {
      return getTxsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTOOrBuilder> 
        getTxsFieldBuilder() {
      if (txsBuilder_ == null) {
        txsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO.Builder, com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTOOrBuilder>(
                txs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        txs_ = null;
      }
      return txsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.thanos.api.proto.push.EthTransactionsPushDTO)
  }

  // @@protoc_insertion_point(class_scope:com.thanos.api.proto.push.EthTransactionsPushDTO)
  private static final com.thanos.api.proto.push.EthTransactionsPushDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.thanos.api.proto.push.EthTransactionsPushDTO();
  }

  public static com.thanos.api.proto.push.EthTransactionsPushDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EthTransactionsPushDTO>
      PARSER = new com.google.protobuf.AbstractParser<EthTransactionsPushDTO>() {
    @java.lang.Override
    public EthTransactionsPushDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EthTransactionsPushDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EthTransactionsPushDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EthTransactionsPushDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.thanos.api.proto.push.EthTransactionsPushDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

