// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.thanos.api.proto.push;

public interface EthTransactionsPushDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.push.EthTransactionsPushDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
   */
  java.util.List<com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO> 
      getTxsList();
  /**
   * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
   */
  com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO getTxs(int index);
  /**
   * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
   */
  int getTxsCount();
  /**
   * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
   */
  java.util.List<? extends com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTOOrBuilder> 
      getTxsOrBuilderList();
  /**
   * <code>repeated .com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTO txs = 1;</code>
   */
  com.thanos.api.proto.push.EthTransactionsPushDTO.EthTransactionPushDTOOrBuilder getTxsOrBuilder(
      int index);
}
