// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.thanos.api.proto.push;

/**
 * Protobuf type {@code com.thanos.api.proto.push.GlobalNodeEventsPushDTO}
 */
public final class GlobalNodeEventsPushDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.thanos.api.proto.push.GlobalNodeEventsPushDTO)
    GlobalNodeEventsPushDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GlobalNodeEventsPushDTO.newBuilder() to construct.
  private GlobalNodeEventsPushDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GlobalNodeEventsPushDTO() {
    nodes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GlobalNodeEventsPushDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GlobalNodeEventsPushDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              nodes_ = new java.util.ArrayList<com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO>();
              mutable_bitField0_ |= 0x00000001;
            }
            nodes_.add(
                input.readMessage(com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        nodes_ = java.util.Collections.unmodifiableList(nodes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_GlobalNodeEventsPushDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_GlobalNodeEventsPushDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.thanos.api.proto.push.GlobalNodeEventsPushDTO.class, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.Builder.class);
  }

  public interface GlobalNodeEventPushDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes hash = 1;</code>
     * @return The hash.
     */
    com.google.protobuf.ByteString getHash();

    /**
     * <code>bytes publicKey = 2;</code>
     * @return The publicKey.
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <code>bytes nonce = 3;</code>
     * @return The nonce.
     */
    com.google.protobuf.ByteString getNonce();

    /**
     * <code>int64 futureEventNumber = 4;</code>
     * @return The futureEventNumber.
     */
    long getFutureEventNumber();

    /**
     * <code>int32 commandCode = 5;</code>
     * @return The commandCode.
     */
    int getCommandCode();

    /**
     * <code>bytes data = 6;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>bytes signature = 7;</code>
     * @return The signature.
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO}
   */
  public static final class GlobalNodeEventPushDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO)
      GlobalNodeEventPushDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GlobalNodeEventPushDTO.newBuilder() to construct.
    private GlobalNodeEventPushDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GlobalNodeEventPushDTO() {
      hash_ = com.google.protobuf.ByteString.EMPTY;
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      nonce_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GlobalNodeEventPushDTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GlobalNodeEventPushDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              hash_ = input.readBytes();
              break;
            }
            case 18: {

              publicKey_ = input.readBytes();
              break;
            }
            case 26: {

              nonce_ = input.readBytes();
              break;
            }
            case 32: {

              futureEventNumber_ = input.readInt64();
              break;
            }
            case 40: {

              commandCode_ = input.readInt32();
              break;
            }
            case 50: {

              data_ = input.readBytes();
              break;
            }
            case 58: {

              signature_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_GlobalNodeEventsPushDTO_GlobalNodeEventPushDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_GlobalNodeEventsPushDTO_GlobalNodeEventPushDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.class, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder.class);
    }

    public static final int HASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString hash_;
    /**
     * <code>bytes hash = 1;</code>
     * @return The hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    public static final int PUBLICKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>bytes publicKey = 2;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int NONCE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString nonce_;
    /**
     * <code>bytes nonce = 3;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }

    public static final int FUTUREEVENTNUMBER_FIELD_NUMBER = 4;
    private long futureEventNumber_;
    /**
     * <code>int64 futureEventNumber = 4;</code>
     * @return The futureEventNumber.
     */
    @java.lang.Override
    public long getFutureEventNumber() {
      return futureEventNumber_;
    }

    public static final int COMMANDCODE_FIELD_NUMBER = 5;
    private int commandCode_;
    /**
     * <code>int32 commandCode = 5;</code>
     * @return The commandCode.
     */
    @java.lang.Override
    public int getCommandCode() {
      return commandCode_;
    }

    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 6;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 7;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!hash_.isEmpty()) {
        output.writeBytes(1, hash_);
      }
      if (!publicKey_.isEmpty()) {
        output.writeBytes(2, publicKey_);
      }
      if (!nonce_.isEmpty()) {
        output.writeBytes(3, nonce_);
      }
      if (futureEventNumber_ != 0L) {
        output.writeInt64(4, futureEventNumber_);
      }
      if (commandCode_ != 0) {
        output.writeInt32(5, commandCode_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(6, data_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(7, signature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!hash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, hash_);
      }
      if (!publicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, publicKey_);
      }
      if (!nonce_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, nonce_);
      }
      if (futureEventNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, futureEventNumber_);
      }
      if (commandCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, commandCode_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, data_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO)) {
        return super.equals(obj);
      }
      com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO other = (com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO) obj;

      if (!getHash()
          .equals(other.getHash())) return false;
      if (!getPublicKey()
          .equals(other.getPublicKey())) return false;
      if (!getNonce()
          .equals(other.getNonce())) return false;
      if (getFutureEventNumber()
          != other.getFutureEventNumber()) return false;
      if (getCommandCode()
          != other.getCommandCode()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + getNonce().hashCode();
      hash = (37 * hash) + FUTUREEVENTNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFutureEventNumber());
      hash = (37 * hash) + COMMANDCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCommandCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO)
        com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_GlobalNodeEventsPushDTO_GlobalNodeEventPushDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_GlobalNodeEventsPushDTO_GlobalNodeEventPushDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.class, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder.class);
      }

      // Construct using com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hash_ = com.google.protobuf.ByteString.EMPTY;

        publicKey_ = com.google.protobuf.ByteString.EMPTY;

        nonce_ = com.google.protobuf.ByteString.EMPTY;

        futureEventNumber_ = 0L;

        commandCode_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_GlobalNodeEventsPushDTO_GlobalNodeEventPushDTO_descriptor;
      }

      @java.lang.Override
      public com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO getDefaultInstanceForType() {
        return com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.getDefaultInstance();
      }

      @java.lang.Override
      public com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO build() {
        com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO buildPartial() {
        com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO result = new com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO(this);
        result.hash_ = hash_;
        result.publicKey_ = publicKey_;
        result.nonce_ = nonce_;
        result.futureEventNumber_ = futureEventNumber_;
        result.commandCode_ = commandCode_;
        result.data_ = data_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO) {
          return mergeFrom((com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO other) {
        if (other == com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.getDefaultInstance()) return this;
        if (other.getHash() != com.google.protobuf.ByteString.EMPTY) {
          setHash(other.getHash());
        }
        if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setPublicKey(other.getPublicKey());
        }
        if (other.getNonce() != com.google.protobuf.ByteString.EMPTY) {
          setNonce(other.getNonce());
        }
        if (other.getFutureEventNumber() != 0L) {
          setFutureEventNumber(other.getFutureEventNumber());
        }
        if (other.getCommandCode() != 0) {
          setCommandCode(other.getCommandCode());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes hash = 1;</code>
       * @return The hash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <code>bytes hash = 1;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes hash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes publicKey = 2;</code>
       * @return The publicKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>bytes publicKey = 2;</code>
       * @param value The publicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes publicKey = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKey() {
        
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString nonce_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes nonce = 3;</code>
       * @return The nonce.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getNonce() {
        return nonce_;
      }
      /**
       * <code>bytes nonce = 3;</code>
       * @param value The nonce to set.
       * @return This builder for chaining.
       */
      public Builder setNonce(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes nonce = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNonce() {
        
        nonce_ = getDefaultInstance().getNonce();
        onChanged();
        return this;
      }

      private long futureEventNumber_ ;
      /**
       * <code>int64 futureEventNumber = 4;</code>
       * @return The futureEventNumber.
       */
      @java.lang.Override
      public long getFutureEventNumber() {
        return futureEventNumber_;
      }
      /**
       * <code>int64 futureEventNumber = 4;</code>
       * @param value The futureEventNumber to set.
       * @return This builder for chaining.
       */
      public Builder setFutureEventNumber(long value) {
        
        futureEventNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 futureEventNumber = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFutureEventNumber() {
        
        futureEventNumber_ = 0L;
        onChanged();
        return this;
      }

      private int commandCode_ ;
      /**
       * <code>int32 commandCode = 5;</code>
       * @return The commandCode.
       */
      @java.lang.Override
      public int getCommandCode() {
        return commandCode_;
      }
      /**
       * <code>int32 commandCode = 5;</code>
       * @param value The commandCode to set.
       * @return This builder for chaining.
       */
      public Builder setCommandCode(int value) {
        
        commandCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 commandCode = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommandCode() {
        
        commandCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 6;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 6;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 7;</code>
       * @return The signature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 7;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO)
    }

    // @@protoc_insertion_point(class_scope:com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO)
    private static final com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO();
    }

    public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GlobalNodeEventPushDTO>
        PARSER = new com.google.protobuf.AbstractParser<GlobalNodeEventPushDTO>() {
      @java.lang.Override
      public GlobalNodeEventPushDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GlobalNodeEventPushDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GlobalNodeEventPushDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GlobalNodeEventPushDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NODES_FIELD_NUMBER = 1;
  private java.util.List<com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO> nodes_;
  /**
   * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO> getNodesList() {
    return nodes_;
  }
  /**
   * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTOOrBuilder> 
      getNodesOrBuilderList() {
    return nodes_;
  }
  /**
   * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
   */
  @java.lang.Override
  public int getNodesCount() {
    return nodes_.size();
  }
  /**
   * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
   */
  @java.lang.Override
  public com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO getNodes(int index) {
    return nodes_.get(index);
  }
  /**
   * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
   */
  @java.lang.Override
  public com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTOOrBuilder getNodesOrBuilder(
      int index) {
    return nodes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < nodes_.size(); i++) {
      output.writeMessage(1, nodes_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < nodes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, nodes_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.thanos.api.proto.push.GlobalNodeEventsPushDTO)) {
      return super.equals(obj);
    }
    com.thanos.api.proto.push.GlobalNodeEventsPushDTO other = (com.thanos.api.proto.push.GlobalNodeEventsPushDTO) obj;

    if (!getNodesList()
        .equals(other.getNodesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNodesCount() > 0) {
      hash = (37 * hash) + NODES_FIELD_NUMBER;
      hash = (53 * hash) + getNodesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.thanos.api.proto.push.GlobalNodeEventsPushDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.thanos.api.proto.push.GlobalNodeEventsPushDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.thanos.api.proto.push.GlobalNodeEventsPushDTO)
      com.thanos.api.proto.push.GlobalNodeEventsPushDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_GlobalNodeEventsPushDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_GlobalNodeEventsPushDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thanos.api.proto.push.GlobalNodeEventsPushDTO.class, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.Builder.class);
    }

    // Construct using com.thanos.api.proto.push.GlobalNodeEventsPushDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNodesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (nodesBuilder_ == null) {
        nodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        nodesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.thanos.api.proto.push.PushGrpcTransport.internal_static_com_thanos_api_proto_push_GlobalNodeEventsPushDTO_descriptor;
    }

    @java.lang.Override
    public com.thanos.api.proto.push.GlobalNodeEventsPushDTO getDefaultInstanceForType() {
      return com.thanos.api.proto.push.GlobalNodeEventsPushDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.thanos.api.proto.push.GlobalNodeEventsPushDTO build() {
      com.thanos.api.proto.push.GlobalNodeEventsPushDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.thanos.api.proto.push.GlobalNodeEventsPushDTO buildPartial() {
      com.thanos.api.proto.push.GlobalNodeEventsPushDTO result = new com.thanos.api.proto.push.GlobalNodeEventsPushDTO(this);
      int from_bitField0_ = bitField0_;
      if (nodesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.nodes_ = nodes_;
      } else {
        result.nodes_ = nodesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.thanos.api.proto.push.GlobalNodeEventsPushDTO) {
        return mergeFrom((com.thanos.api.proto.push.GlobalNodeEventsPushDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.thanos.api.proto.push.GlobalNodeEventsPushDTO other) {
      if (other == com.thanos.api.proto.push.GlobalNodeEventsPushDTO.getDefaultInstance()) return this;
      if (nodesBuilder_ == null) {
        if (!other.nodes_.isEmpty()) {
          if (nodes_.isEmpty()) {
            nodes_ = other.nodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNodesIsMutable();
            nodes_.addAll(other.nodes_);
          }
          onChanged();
        }
      } else {
        if (!other.nodes_.isEmpty()) {
          if (nodesBuilder_.isEmpty()) {
            nodesBuilder_.dispose();
            nodesBuilder_ = null;
            nodes_ = other.nodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            nodesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNodesFieldBuilder() : null;
          } else {
            nodesBuilder_.addAllMessages(other.nodes_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.thanos.api.proto.push.GlobalNodeEventsPushDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.thanos.api.proto.push.GlobalNodeEventsPushDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO> nodes_ =
      java.util.Collections.emptyList();
    private void ensureNodesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        nodes_ = new java.util.ArrayList<com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO>(nodes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTOOrBuilder> nodesBuilder_;

    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public java.util.List<com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO> getNodesList() {
      if (nodesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(nodes_);
      } else {
        return nodesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public int getNodesCount() {
      if (nodesBuilder_ == null) {
        return nodes_.size();
      } else {
        return nodesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO getNodes(int index) {
      if (nodesBuilder_ == null) {
        return nodes_.get(index);
      } else {
        return nodesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public Builder setNodes(
        int index, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.set(index, value);
        onChanged();
      } else {
        nodesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public Builder setNodes(
        int index, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.set(index, builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public Builder addNodes(com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.add(value);
        onChanged();
      } else {
        nodesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public Builder addNodes(
        int index, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.add(index, value);
        onChanged();
      } else {
        nodesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public Builder addNodes(
        com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.add(builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public Builder addNodes(
        int index, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.add(index, builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public Builder addAllNodes(
        java.lang.Iterable<? extends com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO> values) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nodes_);
        onChanged();
      } else {
        nodesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public Builder clearNodes() {
      if (nodesBuilder_ == null) {
        nodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        nodesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public Builder removeNodes(int index) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.remove(index);
        onChanged();
      } else {
        nodesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder getNodesBuilder(
        int index) {
      return getNodesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTOOrBuilder getNodesOrBuilder(
        int index) {
      if (nodesBuilder_ == null) {
        return nodes_.get(index);  } else {
        return nodesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public java.util.List<? extends com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTOOrBuilder> 
         getNodesOrBuilderList() {
      if (nodesBuilder_ != null) {
        return nodesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nodes_);
      }
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder addNodesBuilder() {
      return getNodesFieldBuilder().addBuilder(
          com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder addNodesBuilder(
        int index) {
      return getNodesFieldBuilder().addBuilder(
          index, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
     */
    public java.util.List<com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder> 
         getNodesBuilderList() {
      return getNodesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTOOrBuilder> 
        getNodesFieldBuilder() {
      if (nodesBuilder_ == null) {
        nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO.Builder, com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTOOrBuilder>(
                nodes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        nodes_ = null;
      }
      return nodesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.thanos.api.proto.push.GlobalNodeEventsPushDTO)
  }

  // @@protoc_insertion_point(class_scope:com.thanos.api.proto.push.GlobalNodeEventsPushDTO)
  private static final com.thanos.api.proto.push.GlobalNodeEventsPushDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.thanos.api.proto.push.GlobalNodeEventsPushDTO();
  }

  public static com.thanos.api.proto.push.GlobalNodeEventsPushDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GlobalNodeEventsPushDTO>
      PARSER = new com.google.protobuf.AbstractParser<GlobalNodeEventsPushDTO>() {
    @java.lang.Override
    public GlobalNodeEventsPushDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GlobalNodeEventsPushDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GlobalNodeEventsPushDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GlobalNodeEventsPushDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.thanos.api.proto.push.GlobalNodeEventsPushDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

