// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.thanos.api.proto.push;

public interface GlobalNodeEventsPushDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.push.GlobalNodeEventsPushDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
   */
  java.util.List<com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO> 
      getNodesList();
  /**
   * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
   */
  com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO getNodes(int index);
  /**
   * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
   */
  java.util.List<? extends com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTOOrBuilder> 
      getNodesOrBuilderList();
  /**
   * <code>repeated .com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTO nodes = 1;</code>
   */
  com.thanos.api.proto.push.GlobalNodeEventsPushDTO.GlobalNodeEventPushDTOOrBuilder getNodesOrBuilder(
      int index);
}
