// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.thanos.api.proto.push;

public interface ListBytesObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.push.ListBytesObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes value = 1;</code>
   * @return A list containing the value.
   */
  java.util.List<com.google.protobuf.ByteString> getValueList();
  /**
   * <code>repeated bytes value = 1;</code>
   * @return The count of value.
   */
  int getValueCount();
  /**
   * <code>repeated bytes value = 1;</code>
   * @param index The index of the element to return.
   * @return The value at the given index.
   */
  com.google.protobuf.ByteString getValue(int index);
}
