// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.thanos.api.proto.push;

public interface LongObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.push.LongObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
