// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.thanos.api.proto.push;

public interface StringObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.thanos.api.proto.push.StringObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
